# Generated by Django 6.0.4 on 2026-05-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='game',
            field=models.CharField(choices=[('asteroid_drift', 'Asteroid Drift'), ('echo_match', 'Echo Match'), ('signal_alignment', 'Signal Alignment')], default='asteroid_drift', max_length=50),
        ),
    ]
