# Generated by Django 6.0.4 on 2026-05-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiminalRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('ambient_color', models.CharField(default='#2a003f', max_length=7)),
                ('background_gradient', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('unlock_requirement', models.CharField(blank=True, help_text='Leave blank for always available', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
