# Generated by Django 6.0.4 on 2026-05-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liminalroom',
            name='is_secret',
            field=models.BooleanField(default=False, help_text='Secret rooms are hidden until unlocked via passphrase.'),
        ),
        migrations.AddField(
            model_name='liminalroom',
            name='mars_level',
            field=models.PositiveIntegerField(default=0, help_text='Set to 3 for the secret Mars Level 3 room. 0 = always visible.'),
        ),
    ]
