# Generated by Django 6.0.4 on 2026-05-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lore_flags',
            field=models.JSONField(default=dict, help_text='Lore discoveries. e.g. {"identity": true}'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mars_stage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='memory_log',
            field=models.JSONField(default=list, help_text='Every message the user has ever transmitted to the signal.'),
        ),
    ]
