# Generated by Django 6.0.4 on 2026-05-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('signal_type', models.CharField(choices=[('transmission', 'Transmission'), ('memory', 'Memory Fragment'), ('system', 'System Alert'), ('anomaly', 'Anomaly')], default='transmission', max_length=50)),
                ('stardate', models.CharField(blank=True, max_length=100)),
                ('is_unlocked', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
