# Generated by Django 6.0.4 on 2026-05-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(help_text='The exact phrase the user must type (case-insensitive).', max_length=200)),
                ('room_slug', models.CharField(help_text='The slug of the liminal room this unlocks.', max_length=200)),
                ('unlock_message', models.TextField(default='ACCESS GRANTED. THE ROOM IS OPEN.', help_text='What the signal transmits back when the code is entered correctly.')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignalResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_keywords', models.CharField(help_text='Comma-separated words that trigger this response. e.g. "mars,home,red"', max_length=300)),
                ('response_text', models.TextField(help_text='What the signal transmits back. Will be typed out character by character.')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher number = checked first when multiple keywords match.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-priority'],
            },
        ),
    ]
