# Generated by Django 6.0.4 on 2026-05-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_secretcode_signalresponse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signalresponse',
            options={'ordering': ['mars_stage_min']},
        ),
        migrations.RemoveField(
            model_name='signalresponse',
            name='priority',
        ),
        migrations.AddField(
            model_name='signalresponse',
            name='mars_stage_min',
            field=models.PositiveIntegerField(default=0, help_text='0=always honest, 1=slightly off, 2=unreliable, 3=fully lying/broken'),
        ),
        migrations.AlterField(
            model_name='secretcode',
            name='phrase',
            field=models.CharField(help_text='Case-insensitive passphrase the user must type.', max_length=200),
        ),
        migrations.AlterField(
            model_name='secretcode',
            name='room_slug',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='secretcode',
            name='unlock_message',
            field=models.TextField(default='ACCESS GRANTED. THE ROOM IS OPEN.'),
        ),
        migrations.AlterField(
            model_name='signalresponse',
            name='response_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='signalresponse',
            name='trigger_keywords',
            field=models.CharField(help_text='Comma-separated. e.g. "mars,home,red"', max_length=300),
        ),
    ]
