# Generated by Django 6.0.4 on 2026-05-11 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoryAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_number', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True, help_text='Shown as a brief intro before the entries load.')),
                ('is_active', models.BooleanField(default=True, help_text='If false, this act is completely hidden.')),
                ('unlock_at_mars_stage', models.PositiveIntegerField(default=0, help_text='0 = always visible. 1-3 = unlocks when player reaches that stage.')),
            ],
            options={
                'ordering': ['act_number'],
            },
        ),
        migrations.CreateModel(
            name='StoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(choices=[('PERFECTION', 'PERFECTION'), ('SIGNAL', 'SIGNAL'), ('SYSTEM', 'SYSTEM')], default='PERFECTION', max_length=20)),
                ('entry_type', models.CharField(choices=[('log', "Captain's Log"), ('transmission', 'Transmission'), ('system_alert', 'System Alert'), ('recovered_file', 'Recovered File'), ('redacted', 'Redacted')], default='log', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('stardate', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField()),
                ('signal_version', models.TextField(blank=True, help_text="The signal's version of this same event. Leave blank if none.")),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_unlocked', models.BooleanField(default=True)),
                ('unlock_at_mars_stage', models.PositiveIntegerField(default=0, help_text='0 = always visible if is_unlocked is true.')),
                ('is_corrupted', models.BooleanField(default=False, help_text='Renders content with a glitch/corruption effect.')),
                ('is_redacted', models.BooleanField(default=False, help_text='Shows the entry but blacks out content with redaction bars.')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='storyline.storyact')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
